# Generated by Django 4.0.2 on 2022-02-13 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('release', models.DateField()),
                ('duration', models.DurationField(help_text="value must be in '%d %H:%M:%S.%f' format.")),
                ('description', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'Movies',
                'ordering': ('-rating', '-release', 'name'),
                'unique_together': {('name', 'release')},
            },
        ),
    ]
